name: Release Notes

on:
  push:
    tags: '*'

jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get previous tag
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          PREVIOUS_TAG=$(git describe --tags `git rev-list --tags --max-count=2` | tail -n 1 || echo '')
          if [ "$TAG" = "$PREVIOUS_TAG" ]; then
              PREVIOUS_TAG=''
          fi
          echo "Previous tag: $PREVIOUS_TAG"
          echo "tag: $TAG"
      - name: Get commits since previous tag
        run: |
          if [ -z "$PREVIOUS_TAG" ]; then
            COMMITS=$(git log --oneline --no-merges)
          else
            COMMITS=$(git log --oneline $PREVIOUS_TAG..$TAG --no-merges)
          fi
          echo "Commits since previous tag:"
          echo "$COMMITS"
          CHANGELOG=$(echo "$COMMITS" | sed -e 's/^\([^ ]*\) \(.*\)$/\1: \2/g')
          echo "$CHANGELOG"
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{env.CHANGELOG}}
